AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple Lambda based HTTP service template

Globals:
  Function:
    Timeout: {{service_instance.lambda_timeout}}
    Tracing: Active
    MemorySize: {{service_instance.lambda_memory}}

Resources:
  CrudHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      FailOnWarnings: false
{% if service_instance.code_uri|length %}
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "{{service_instance.code_uri}}"
      Handler: "{{service_instance.resource_handler}}.list_{{service_instance.resource_name}}"
      Runtime: "{{service_instance.lambda_runtime}}"
      Environment:
        Variables:
          TABLE_NAME: "{{environment.TableName}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{environment.TableName}}"
      Events:
        ListApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CrudHttpApi
            Path: "/{{service_instance.resource_name}}"
            Method: GET
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "{{service_instance.code_uri}}"
      Handler: "{{service_instance.resource_handler}}.create_{{service_instance.resource_name}}"
      Runtime: "{{service_instance.lambda_runtime}}"
      Environment:
        Variables:
          TABLE_NAME: "{{environment.TableName}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{environment.TableName}}"
      Events:
        CreateApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CrudHttpApi
            Path: "/{{service_instance.resource_name}}"
            Method: POST
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "{{service_instance.code_uri}}"
      Handler: "{{service_instance.resource_handler}}.get_{{service_instance.resource_name}}"
      Runtime: "{{service_instance.lambda_runtime}}"
      Environment:
        Variables:
          TABLE_NAME: "{{environment.TableName}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{environment.TableName}}"
      Events:
        GetApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CrudHttpApi
            Path: "/{{service_instance.resource_name}}/{id}"
            Method: GET
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "{{service_instance.code_uri}}"
      Handler: "{{service_instance.resource_handler}}.delete_{{service_instance.resource_name}}"
      Runtime: "{{service_instance.lambda_runtime}}"
      Environment:
        Variables:
          TABLE_NAME: "{{environment.TableName}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{environment.TableName}}"
      Events:
        DeleteApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CrudHttpApi
            Path: "/{{service_instance.resource_name}}/{id}"
            Method: DELETE
  UpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: "{{service_instance.code_uri}}"
      Handler: "{{service_instance.resource_handler}}.update_{{service_instance.resource_name}}"
      Runtime: "{{service_instance.lambda_runtime}}"
      Environment:
        Variables:
          TABLE_NAME: "{{environment.TableName}}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "{{environment.TableName}}"
      Events:
        UpdateApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref CrudHttpApi
            Path: "/{{service_instance.resource_name}}/{id}"
            Method: PATCH
{% endif %}
Outputs:
  HttpApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${CrudHttpApi}.execute-api.${AWS::Region}.amazonaws.com/{{service_instance.resource_name}}"
