name: My Workflow
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run action
      # Put your action repo here
      uses: kohidave/proton-jinja-template-validation-action
