name: Validate Updated Templates
on:
  pull_request:
    branches: [ "main" ]
jobs:
  TemplateChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        separator: ","
    - name: Validate changed templates
      uses: aws-samples/aws-proton-template-checker-action@v1.0
      with: 
        changed_files: "${{steps.changed-files.outputs.all_changed_files}}"
